### ISSUE TITLE
Show partition labels when detecting GRUB configs

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#72] opened 2020-03-04 02:53 UTC
Hi! When I "boot manually" by searching for GRUB config files, SGD shows just the disk numbers. Could you add the partition labels there? This would help a lot when I have several disks with GRUBs connected.

**Comment by adrian15** [comment] 2021-03-16 19:40
I might do it. If there is no label then I should show '(no label)' isn't it ?

**Comment by mk-pmb** [comment] 2021-03-16 20:22
Yes, good idea.

**Comment by adrian15** [comment] 2024-04-28 10:27
Isn't this issue a duplicate of https://github.com/supergrub/supergrub/issues/47 ?

If they are not duplicates please explain why.

Thank you!

**Comment by mk-pmb** [comment] 2024-04-28 20:05
I'm not sure, it's been a long time. I think it's the same problem but in different menus.

**Comment by adrian15** [comment] 2024-05-25 14:16
> I'm not sure, it's been a long time. I think it's the same problem but in different menus. I'm no longer affected though (see other thread).

Closing the issue then.

**Closed by adrian15** 2024-05-25 14:16 UTC
