### ISSUE TITLE
BTRFS subvolumes as root

### ISSUE THREAD

**Issue by petsam** [supergrub/supergrub#86] opened 2021-08-17 01:04 UTC
It is proposed (and some distros apply this) for btrfs systems, to not use subvolid=5 for root, using subvolumes for all mounted "mounts" instead.

This means that they compile grub's `linux` command using `/@/` as the system root directory, instead of `/`. Garuda (that I know of) and maybe others, like Ubuntu(?) or Fedora, have to apply a patch to Grub, in order to recognize these paths. Otherwise, they are not. Unmodified grubs cannot "see" those systems, when using `os-prober`, as I know it happens in Archlinux upstream grub.

Since your (EXCELLENT) utility serves a recovery purpose, you may want to add these paths to your discovery tools.

For example, in `cfgdetect.cfg` and `cfgextract.cfg`, change 
```
for ncfgpath in boot/grub/grub.cfg grub/grub.cfg boot/grub2/grub.cfg \
        grub2/grub.cfg ; do
```
to
```
for ncfgpath in boot/grub/grub.cfg grub/grub.cfg boot/grub2/grub.cfg \
        grub2/grub.cfg @/boot/grub/grub.cfg @/grub/grub.cfg \
		@/boot/grub2/grub.cfg @/grub2/grub.cfg ; do
```
I have not tried it yet, so you may know better how to implement safely.

I suppose it is obvious that all discovery `.cfg`s need this implementation, like os-detect.cfg (run_option) and more that I haven't finished examining yet.

I saw a zfs for FreeBSD check with subvolumes. Something similar, but for btrfs and for all linux (`else` part in run_option). 

I suppose some function and/or `if` check for this would narrow down the work, but you already know that.

I would be glad to help, in any way you may ask.

Thanks for this tool. It was the utility that saved me from broken systems, in my first steps in Linux (long time ago). It sounds awesome if I can contribute to it, now that I know a lot more about Linux and Grub2. :smiley:

**Comment by thermon** [comment] 2024-01-04 11:32
Yay, I've implemented your idea.
I was also disappointed that SuperGrub could not search the boot directory inside the btrfs subvolume.
It would be better if this was merged into the main stream.
![supergrub_on_btrfs](https://github.com/supergrub/supergrub/assets/123725/746aab12-ea24-4445-9cc7-eba65716e387)

**Comment by adrian15** [comment] 2024-04-28 10:50
> I would be glad to help, in any way you may ask.

Any distro that I can install that uses BTRFS by default (automatic install) in such a way that it is not detected by SG2D so that I can test this myself without too much of as hassle?

**Comment by adrian15** [comment] 2024-04-28 10:51
> Yay, I've implemented your idea. I was also disappointed that SuperGrub could not search the boot directory inside the btrfs subvolume. It would be better if this was merged into the main stream. ![supergrub_on_btrfs](https://private-user-images.githubusercontent.com/123725/294167047-746aab12-ea24-4445-9cc7-eba65716e387.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDE0MTIsIm5iZiI6MTcxNDMwMTExMiwicGF0aCI6Ii8xMjM3MjUvMjk0MTY3MDQ3LTc0NmFhYjEyLWVhMjQtNDQ0NS05Y2M3LWViYTY1NzE2ZTM4Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxMDQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODRhNjkyZjg5YzNlNDU0MWY1MjMwZjhiNjg5M2NjZTEyN2JiYzllMmRlYzM4MjJiZmI0NTkwMDk0NzA0ZmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4A07Kuyeqw5gBarDz0EcaQ6hAUZOghwueCv3Tol7-Q8)

Have you tested your change with non BTRFS distros? Does give it any problem?

**Comment by adrian15** [comment] 2024-04-28 11:03
The _Boot manually..._ option tries let's you boot an specific kernel + initrd combination that it's usually found on the regular /boot partition.

1) Should we also search for those kernel + initrd in subvolumes the same way you are suggesting to search for grub.cfg files?

2) And... is there any specific Kernel boot option that we should using when booting into the Kernel and Initrd?
I mean, the FreeBSD kernel parametres for direct Kernel booting were quite different between booting from an UFS filesystem boot and booting from a ZFS filesystem boot.

3) Maybe you could share an specific grub.cfg snippet from your system regarding how a normal Linux entry looks like.

Thank you.

**Comment by thermon** [comment] 2024-04-29 04:13
Yes,I finaly edited osdetect.cfg.
As a result, 'rootflags=subvol=@' is added to the kernel option when using a btrfs file system.

**Comment by thermon** [comment] 2024-04-29 06:26
tthese are edited sources.

https://github.com/thermon/supergrub

**Comment by adrian15** [comment] 2024-05-12 19:38
Thanks to the [thermon's pull](https://github.com/supergrub/supergrub/pull/106) I have started to work on this.

You can check: https://github.com/supergrub/supergrub/tree/2.06s3-dev2 which I have actually not tested but has everything that I think should be there.

**Comment by adrian15** [comment] 2024-05-15 05:36
> In btrfs file system, may be cases where there is no @subvolume in file system, I think it is better to judge by the path of the boot file rather than by the file system.

Isn't that the way I have finally implemented it ?

**Comment by thermon** [comment] 2024-05-16 12:45
Yes it is,but that's not enough.

>     regexp -s 2:subvol '((|/@)/boot)/(vmlinuz|linux|kernel-genkernel)-(.*)' $kernel
>     if test $fstype = "btrfs" -a $subvol ;then
>       linux $kernel root=UUID=$uuid ro rootflags=subvol=$subvol ${kernel_option}
>     else
>       linux $kernel root=UUID=$uuid ro ${kernel_option}
>     fi

Kernel options are required when there are subvolumes, but kernel options are not required when there are no subvolumes.

**Comment by thermon** [comment] 2024-05-16 12:48
Yes it is,but that's not enough.

>     regexp -s 2:subvol '((|/@)/boot)/(vmlinuz|linux|kernel-genkernel)-(.*)' $kernel
>     if test $fstype = "btrfs" -a $subvol ;then
>       linux $kernel root=UUID=$uuid ro rootflags=subvol=$subvol ${kernel_option}
>     else
>       linux $kernel root=UUID=$uuid ro ${kernel_option}
>     fi

Rootflags kernel option is required when there are subvolumes, but it is not required when there are no subvolumes.

**Comment by adrian15** [comment] 2024-05-19 18:08
Ok, @thermon, I'm going to close both of your pull requests because I have added some of your code.

If you think anything can be improved **make sure to make your commits from 2.06s3-dev7 branch**.

**Do not reuse your old commits.**

- [2.06s3-dev7 branch](https://github.com/supergrub/supergrub/tree/2.06s3-dev7)

**Comment by petsam** [comment] 2024-05-24 22:20
> Any distro that I can install that uses BTRFS by default

Garuda Linux (exclusively btrfs) and EndeavourOS (select in installer).

If I can find some spare time, I could test the new work.

**Comment by adrian15** [comment] 2024-05-26 15:11
**Update**

If you think anything can be improved make sure to make your commits from [2.06s3-dev9](https://github.com/supergrub/supergrub/tree/2.06s3-dev9) branch.

Do not reuse your old commits.

**Comment by adrian15** [comment] 2024-06-01 13:16
Ok, I have a question for you the BTRFS guys.

How does the `root=UUID=$uuid` part works exactly?

I think that with the current code that I have in [2.06s3-dev9](https://github.com/supergrub/supergrub/tree/2.06s3-dev9) branch we are enforcing the UUID of the BTRFS partition... not of the BTRFS volume.

So maybe what I'm asking for is: Do the BTRFS volumes have an UUID of their own and we need to improve this or if it's just fine because the BTRFS partition has an UUID and that's it?

Thank you!

**Comment by adrian15** [comment] 2024-06-02 06:40
[Super Grub2 Disk  2.06s3-beta3](https://sourceforge.net/projects/supergrub2/files/2.06s3-beta3/) has been released.

Please give me feedback about BTRFS as I haven't setup a VM test with a BTRFS distro yet.

If you think anything can be improved make sure to make your commits from [2.06s3-dev20](https://github.com/supergrub/supergrub/tree/2.06s3-dev20) branch. **Do not reuse your old commits.**

**Comment by thermon** [comment] 2024-06-02 09:43
There is no problem with the current implementation. This is because the
uuid of the btrfs volume and the uuid of each btrfs partition are the same.
Don't worry.

2024年6月2日(日) 15:40 adrian15 ***@***.***>:

**Comment by adrian15** [comment] 2024-06-02 10:43
Ok, thank you for the UUID feedback.

Now waiting for your 2.06s3-beta3 version feedback on the BTRFS and BTRFS multi volume support on actual BTRFS systems.

Thank you!

**Comment by adrian15** [comment] 2024-06-08 15:46
I was thinking about another option which it's **core.img - GRUB2 installation** [grubdetect.cfg](https://github.com/supergrub/supergrub/blob/2.06s3-dev20/menus/sgd/grubdetect.cfg).

So the question is... Are you supposed to have any of these files:

 - boot/grub/i386-pc/core.img
- grub/i386-pc/core.img
- boot/grub2/i386-pc/core.img
- grub2/i386-pc/core.img
- boot/grub/core.img
- grub/core.img
- boot/grub2/core.img
- grub2/core.img
- boot/grub/core.img

 in a BTRFS subvolume or is it something that never happens?

**Comment by adrian15** [comment] 2024-06-08 17:42
Please test: https://github.com/supergrub/supergrub/tree/2.06s3-dev23 I cannot release a beta for now.

**Comment by thermon** [comment] 2024-06-09 11:01
I tried modifying the grubdetect.cfg that you pointed out and the parts that I was personally concerned about.
We have confirmed the operation in the sense that it is displayed on the SG2 screen.

![20240609194922_p](https://github.com/supergrub/supergrub/assets/123725/3f863ff5-ddc7-47db-8faf-283afbcf2faf)
![20240609194945_p](https://github.com/supergrub/supergrub/assets/123725/d54af3a2-bf14-4245-b6f8-117c4effac65)
![20240609193656_p](https://github.com/supergrub/supergrub/assets/123725/555f51d5-441e-4f28-9449-58839e4f8ef6)

**Comment by adrian15** [comment] 2024-06-15 19:26
Please test: https://github.com/supergrub/supergrub/tree/2.06s3-dev24 I cannot release a beta for now.

**Comment by thermon** [comment] 2024-06-16 10:10
I confirmed that it works properly.

![IMG20240616190232](https://github.com/supergrub/supergrub/assets/123725/ae3c707d-e615-4b44-859c-473ae146bcef)

**Comment by adrian15** [comment] 2024-06-16 16:02
> I confirmed that it works properly.
> 
> ![IMG20240616190232](https://private-user-images.githubusercontent.com/123725/340082869-ae3c707d-e615-4b44-859c-473ae146bcef.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTM5NTMsIm5iZiI6MTcxODU1MzY1MywicGF0aCI6Ii8xMjM3MjUvMzQwMDgyODY5LWFlM2M3MDdkLWU2MTUtNGI0NC04NTljLTQ3M2FlMTQ2YmNlZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQxNjAwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzZlMDczNGM5YTIyNjFlMjFiZmM5NzI1MjExZjBmNWJhNjA3ZjBjZTNjYTVhZjg1ZTdjZWJmZGQwYjljOTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bV8kTprWk1Zp9mcEv6mLKvU7eo05cIdulqzZ0gaZBWQ)

Finally :) .

Thanks!

I'll leave the issue open some days just in case @petsam wants to give us his feedback.

**Comment by adrian15** [comment] 2024-06-23 08:37
This functionality will soon make out its way onto a beta so I'm closing this issue for now.

**Comment by adrian15** [comment] 2024-06-30 08:41
Could you please test https://github.com/supergrub/supergrub/tree/2.06s3-dev44 ?

In addition to the old boot options I'm also interested in you to the new option named 'Linux from /boot' partition.

Please notice that if you want to test this in your actual system you might need to copy manually your `vmlinuz-*` and `initrd-*` files from `/boot` directory to the `/` directory in order to simulate that you have a `/boot` partition.

**Comment by thermon** [comment] 2024-06-30 13:26
I tried creating two pairs of / and /boot, but they do not correspond to the correct / partition.
To achieve this, it seems necessary to analyze the contents of /etc/fstab.
![20240630221724_p](https://github.com/supergrub/supergrub/assets/123725/8608b97b-1151-45b1-9758-581dff9d9700)

**Comment by adrian15** [comment] 2024-06-30 14:23
> I tried creating two pairs of / and /boot, but they do not correspond to the correct / partition. To achieve this, it seems necessary to analyze the contents of /etc/fstab. ![20240630221724_p](https://private-user-images.githubusercontent.com/123725/344468208-8608b97b-1151-45b1-9758-581dff9d9700.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NTc0NzEsIm5iZiI6MTcxOTc1NzE3MSwicGF0aCI6Ii8xMjM3MjUvMzQ0NDY4MjA4LTg2MDhiOTdiLTExNTEtNDViMS05NzU4LTU4MWRmZjlkOTcwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQxNDE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2U4Njc2MWZhNzk1ODI0ZmM1YWY4YjQ5ZmIyMzM0MmI1ZTc0NjY4N2Y2M2M3ZWMxMTM5Y2FmYWM0OGM1MjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f8uo8E-lRMzMiIRahhA8Z9zb7Us8Kf6WP_Z4vm_-HWI)

Well, that's the expected behaviour.
You need to know which it's your distro partition (the one that has /etc/fstab) and then you select the kernel from the /boot partition which you also should know as a power-user that have a custom /boot partition.

I had thought about reading /etc/issue for the distro label but unfortunately with Grub 2.06 you cannot do that.

What I'm interested to know if you move the vmlinuz-* and initrd-* to a btrfs volume / directory...
  Is it properly shown as a kernel that you can choose from the 'Linux from /boot partition' ?

**Comment by thermon** [comment] 2024-07-01 05:50
Is this OK?
![20240701144418_p](https://github.com/supergrub/supergrub/assets/123725/6bd080cf-2079-4541-8fe1-fe5809979f94)

**Comment by adrian15** [comment] 2024-07-01 06:32
> Is this OK? ![20240701144418_p](https://private-user-images.githubusercontent.com/123725/344558255-6bd080cf-2079-4541-8fe1-fe5809979f94.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTMzNTYsIm5iZiI6MTcxOTgxMzA1NiwicGF0aCI6Ii8xMjM3MjUvMzQ0NTU4MjU1LTZiZDA4MGNmLTIwNzktNDU0MS04ZmUxLWZlNTgwOTk3OWY5NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNTUwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmQyOTRmMjcwN2VmOWEyZDRmMzhlMzA1OGVkOTY5YTliODg5MzhhMThmYTYyMzE3YTllZmIxYWFkOTE5ZDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fWYrZ2vE_TBhVf7PkF00rSI3xRmuoBZQJoTRqDix0cw)

Well, I guess so.

The second line which has `(lvm/main-ubuntu) btrfs with Linux kernel:` is a distro (its /etc/fstab has been detected).
If you select fourth line `- /vmlinuz-6.5.0-26-generic (lvm/main-xubuntu--boot)` you are trying to boot that distro with this specific kernel (and its associated initrd) which it's found inside of the `/` directory of a btrfs volume which I guess it's called `lvm/main-xubuntu-boot`.

What I have never understood of your screenshots is that you have a btrfs volume named `lvm/main-xubuntu--boot`. Is that right? Is that they way you are supposed to name your btrfs volumes? Why `lvm` string is in it ?

**Comment by adrian15** [comment] 2024-07-01 06:45
Ok, I see `lvm/main-xubuntu-boot` must an LVM's LV.

I want the vmlinuz and initrd files to be found in a btrfs volume so that a `@/something` appears somewhere.

You know... the same thing you did with the normal Linux entries (according to your screenshots)... We should have a `@/` somewhere while selecting the kernel.

**Comment by thermon** [comment] 2024-07-01 09:39
I got iit.This is what it means. Regardless of the need to put `boot `into a subvolume.
![20240701183143_p](https://github.com/supergrub/supergrub/assets/123725/dbaed8a0-2803-4b11-8b68-c5802a3fa5f8)

**Comment by thermon** [comment] 2024-07-01 16:03
I did it! I've used file system labels to associate the root file system with the boot file system.
![20240702005508_p](https://github.com/supergrub/supergrub/assets/123725/7813228a-de84-4a04-97b1-45b45af71d43)

**Comment by adrian15** [comment] 2024-07-01 19:21
Yes, you did it. Thank you very much!

**Comment by adrian15** [comment] 2024-07-01 19:24
@petsam If you want to give it a go and building SG2D yourself is a problem you can use this latest release: https://sourceforge.net/projects/supergrub2/files/2.06s3-beta4/ .

**Comment by petsam** [comment] 2024-07-02 17:39
Test was successful!! Good job!

My specific interest on supergrub usage was as an addon to the system default grub/grub.cfg.
I am interested only in the menus, which I add to `/boot/grub/` as `sgd` folder and a custom entry in `/etc/grub.d/45_sgd` to check for `sgd` folder and add a menu entry for `main.cfg` (I can post file contents and instructions, if you want). While in the old version (when I first opened my issues) I had to do several modifications, now it was working OOTB!!! Perfectly!

One _odd_ thing noticed, though, which may probably be _normal function_, or my misunderstanding.
SGD discovered everything on my drives (even Windows and a very old BTRFS installation, booted into them and updated OSes), except my main system efi entry/ESP partition. Is this normal? Something with loopback, or something else?

In any case, it works fine with BTRFS subvolumes (tested, booted, as expected). :+1:

**Comment by adrian15** [comment] 2024-07-02 21:04
> Test was successful!! Good job!
> 
> My specific interest on supergrub usage was as an addon to the system default grub/grub.cfg. I am interested only in the menus, which I add to `/boot/grub/` as `sgd` folder and a custom entry in `/etc/grub.d/45_sgd` to check for `sgd` folder and add a menu entry for `main.cfg` (I can post file contents and instructions, if you want). While in the old version (when I first opened my issues) I had to do several modifications, now it was working OOTB!!! Perfectly!

Well, that sounds quite similar to [RFE: Super Grub2 Disk (Mini)](https://github.com/supergrub/supergrub/issues/69) so you might participate there with your feedback.

> One _odd_ thing noticed, though, which may probably be _normal function_, or my misunderstanding. SGD discovered everything on my drives (even Windows and a very old BTRFS installation, booted into them and updated OSes), except my main system efi entry/ESP partition. Is this normal? Something with loopback, or something else?

Extra GRUB2 functionality. Search in Super Grub2 Disk device. You might need to turn that on. That's off by default.
 
> In any case, it works fine with BTRFS subvolumes (tested, booted, as expected). 👍

Nice!

**Closed** 2024-07-30 20:34 UTC
Labels: 2024, 2024-fixed-in-dev-branch

**Comment by thermon** [comment] 2024-07-31 06:06
Congratulations!

2024年7月31日(水) 5:34 adrian15 ***@***.***>:
