### ISSUE TITLE
Latest SuperGRUB2 is not booting ISO saved in the folders it specifies

### ISSUE THREAD

**Issue by CollaboratorGCM** [supergrub/supergrub#53] opened 2019-11-03 00:31 UTC
I am a Puppy Linux user who has tried unsuccessfully to use SG2 V2.04 to boot Puppy Linux ISOs. I have run into several problems when running either a CD to boot or a USB stick to boot ISOs.
1. Placing ISO files on HDD in the /boot and /boot/boot-sios will NOT be found by SG2 as OS candidates for boot
2. ONLY placing ISOs on HDD in /boot-isos will be seen BUT ONLY the ISO SG2 is set for...not the PUP ISOs

My initial intent was to add ISOs to the SuperGRUB2 USB stick. BUT your ISO creates a ISO9660 partition where NOTHING can be added to the USB stick.

Lastly, on GIT at this location ( https://github.com/puppylinux-woof-CE/woof-CE/issues/1618#issuecomment-548973021 ) PUP developers are trying to achieve something I think @adrian15 has knowledge to make their life easy as they try to standardize on GRUB2. In fact for a 16MB SG2, Puppy could make SG2 its boot-loader to reduce their efforts in GRUB2 use.

If considered, SG2 could become their bootmanager and it would expand the number of SG2 developers working in concert here.

**EDIT: UPDATE!!!** This thread was opened with some bad understanding due in part by having trying to use the "wrong" SG2D. After being guided to the latest and proper SG2D ISO greater success was achieved.

In my case, the ONLY ISOs that I was able to have SG2D select for booting are the ONLY ones that have a loopback.cfg. ALL OTHER ISOs were ignored.

**Comment by adrian15** [comment] 2019-11-03 09:10
> I am a Puppy Linux user who has tried unsuccessfully to use SG2 V2.04 to boot Puppy Linux ISOs.

There is no such thing as SG2 V2.04 please use the right name, version and media to refer to Super Grub2 Disk.

**Comment by CollaboratorGCM** [comment] 2019-11-03 09:11
Give me one moment and I will give name and the link from your site....

**Comment by adrian15** [comment] 2019-11-03 09:15
> 1. Placing ISO files on HDD in the /boot and /boot/boot-sios will NOT be found by SG2 as OS candidates for boot
> 2. ONLY placing ISOs on HDD in /boot-isos will be seen BUT ONLY the ISO SG2 is set for...not the PUP ISOs
> 
> My initial intent was to add ISOs to the SuperGRUB2 USB stick. BUT your ISO creates a ISO9660 partition where NOTHING can be added to the USB stick.

Well, this issue you describe has been resolved in the latest beta (2.04s2-beta2). Do not use the cdrom bootable image (iso) but multiarch USB image instead. That image features an additional BOOTISOS partition for you to put ISO files there.

And as a bonus the SG2D core partition can be also edited (although you shouldn't need to edit it).

**Comment by CollaboratorGCM** [comment] 2019-11-03 09:18
The reason I saw to add to the partition was to add the ISO to its /boot folder. My USBs are reasonably large for the small ISOs PUPPY Linuxes are. On the ISO9660 I cannot do this after USB creation. 

But if the partition is formated other than that, I should be able to update the USB so that the SG2 USB would contain all needs for boots

**Comment by CollaboratorGCM** [comment] 2019-11-03 09:21
OH, and I must congratulate you over the years you have been producing your work. EXCELLENT insights and perspective in your works.

Thanks in advance as you guide

**Comment by adrian15** [comment] 2019-11-03 09:25
> I am a Puppy Linux user who has tried unsuccessfully to use supergrub2-2.04s2-beta2-multiarch-USB.img.zip to boot Puppy Linux ISOs. I have run into several problems when running either a CD to boot or a USB stick to boot ISOs.
> 
> Placing ISO files on HDD in the /boot and /boot/boot-sios will NOT be found by SG2 as OS candidates for boot
Do you mean an internal HDD ?
Which partition filesystem were you using?

Anyway the supported paths as [Loopback.cfg page](https://www.supergrubdisk.org/wiki/Loopback.cfg#How_do_you_use_a_loopback.cfg_to_boot_an_iso.3F) says are:
 - /boot/boot-isos
 - /boot-isos
 - /boot/bootisos
 - /bootisos

And, well, as I explain in https://github.com/supergrub/supergrub/issues/50 in the most common cases you need to make sure that a loopback.cfg is supplied inside the iso itself.

> ONLY placing ISOs on HDD in /boot-isos will be seen BUT ONLY the ISO SG2 is set for...not the PUP ISOs

Sorry this text _the ISO SG2 is set for...not the PUP ISOs_ seems to be incomplete. I cannot understand it. Can you please rephrase it? Thank you.

**Comment by CollaboratorGCM** [comment] 2019-11-03 09:27
On my HDD in the folder /mnt/sdb1 I currently have moved the ISOs prior to appealing for help. Before moving them, SG2 could NOT find ISOs.

The 2 files downloaded from your site and used to create USB bootable SG2 is super
- grub2-2.04s2-beta2-multiarch-CD.iso
- super_grub2_disk_hybrid_2.04rc1s1-beta4.iso
Are either the correct one(s)?

**Comment by adrian15** [comment] 2019-11-03 09:28
> The reason I saw to add to the partition was to add the ISOs to its /boot folder.

To add to the partition ? What?
Please rephrase your entire phrase so that it makes sense.

**Comment by CollaboratorGCM** [comment] 2019-11-03 09:31
I have your distro structure on the bootable USB. I wanted to add the ISOs to that USB so that the USB stick contains its bootable and the ISO(s) that I would boot. ISO9660 does not allow any changes to the folders on the USB. Nor does ISOmaster modify and recreate a new ISO in that format.

**Comment by adrian15** [comment] 2019-11-03 09:32
> On my HDD in the folder /mnt/sdb1 I currently have moved the ISOs prior to appealing for help. Before moving them, SG2 could NOT find ISOs.
> 
> The 2 files downloaded from your site and used to create USB bootable SG2 is
> 
> * supergrub2-2.04s2-beta2-multiarch-CD.iso
> * super_grub2_disk_hybrid_2.04rc1s1-beta4.iso
>   Are either the correct one(s)?

For what you want to do, as I said before in:

> Well, this issue you describe has been resolved in the latest beta (2.04s2-beta2). Do not use the cdrom bootable image (iso) but multiarch USB image instead. That image features an additional BOOTISOS partition for you to put ISO files there.
> 
> And as a bonus the SG2D core partition can be also edited (although you shouldn't need to edit it)

you need to use supergrub2-2.04s2-beta2-multiarch-USB.img.zip .

**Comment by adrian15** [comment] 2019-11-03 09:37
> On my HDD in the folder /mnt/sdb1 I currently have moved the ISOs prior to appealing for help. Before moving them, SG2 could NOT find ISOs.

Before moving them ? To where?
I'm not a pithoness ;) .

**Comment by adrian15** [comment] 2019-11-03 09:41
> I got this distro https://sourceforge.net/projects/supergrub2/files/2.04s2-beta2/super_grub2_disk_2.04s2-beta2/supergrub2-2.04s2-beta2-multiarch-USB.img.zip/download

> The 2 files downloaded from your site and used to create USB bootable SG2 is
> 
> * supergrub2-2.04s2-beta2-multiarch-CD.iso
> * super_grub2_disk_hybrid_2.04rc1s1-beta4.iso
>   Are either the correct one(s)?

One of these statements should not be true.
Either you have used supergrub2-2.04s2-beta2-multiarch-USB.img.zip or supergrub2-2.04s2-beta2-multiarch-CD.iso . Please be specific enough when answering to me because sometimes the different medias have differences.

**Comment by CollaboratorGCM** [comment] 2019-11-03 09:46
In the current SG2 version I burned to USB, I have ALL of my ISOs on /mnt/sdb2 (my error from before). I started by placing all ISO in /boot/boot-isos. Booting the USB it did not find the ISOs on that HDD folder. I moved them from /boot/boot-isos to /boot-isos and rebooted SG2 USB. It did not find the ISOs on the HDD. So curiously I move all ISOs to /mnt/sdb1 (root) and rebooted. SG2 did find some but did not display any of the PUPPY ISOs.

I will download and follow your instructions. I will do so and report success as soon as possible. And, I will return **here** with the results.

Thanks for your guidance **thus far**.
**P.S.** Hope you had a chance to look over the GITHUB link for Puppy Linux I enclosed earlier. If this works for what I am doing, I can see its potential in what they want to do moving from syslinux to GRUB2 (or SuperGRUB2 as their boot management solution)

**Comment by adrian15** [comment] 2019-11-03 09:51
> Is there documentation that addresses how to boot ISOs which would describe the following:

Most similar webpages to what you are asking are:
 - https://www.supergrubdisk.org/wiki/Loopback.cfg
 - https://github.com/supergrub/supergrub/blob/master/menus/sgd/autoiso.cfg

I might recreate Loopback.cfg either on supergrub github or [live id github](https://github.com/rescatux/liveid/blob/master/LIVEID_PROPOSAL_1.md).

> * The drive-type requirement? (**MSDOS** or **GPT** or it does not matter)

It shouldn't matter.

> * The partition format it will search? (**EXTx** or **FAT32** or **NTFS** or **F2FS** or it does not matter)

Not sure if SG2D supports F2FS. Can you try to ls the F2FS partition from SG2D grub shell and report back maybe in a new issue if it does not work?

> * Which partition it will ONLY search? (Will it cycle thru all drives and all partitions on each drive looking for its folder of ISOs)

It only excludes the SG2D partition (and that can be changed thanks to a variable).

> * The actual folder names it looks for along with its order of search? (**/boot-isos** or **/boot** or **/boot/boot-isos** or all the above or ???)

I have already explained it in this thread.

> Maybe there is a wiki or site or youtube or PDF document showing steps to **"setting up and booting ISOs"** which can be replicated?

Pull requests are welcome.

**Comment by adrian15** [comment] 2019-11-03 09:57
> OH, and I must congratulate you over the years you have been producing your work. EXCELLENT insights and perspective in your works.
> 
> Thanks in advance as you guide

If you want to thank back please try latest Rescatux betanand give us feedback on https://github.com/rescatux/rescapp/issues .

**Comment by adrian15** [comment] 2019-11-03 10:05
> In the current SG2 version I burned to USB, I have ALL of my ISOs on /mnt/sdb2 (my error from before).

Please do not use "/mnt/sdb2" as a term. It doesn't mean anything to me. Use second partition from internal hard disk instead (or whatever it is).

> I started by placing all ISO in /boot/boot-isos. Booting the USB it did not find the ISOs on that HDD folder.

The menu in SG2D says that it find isos in /boot/boot-isos isn't it ? You were doing something else. So that's an expected behaviour.


> I moved them from /boot/boot-isos to /boot-isos and rebooted SG2 USB. It did not find the ISOs on the HDD. So curiously I move all ISOs to /mnt/sdb1 (root) and rebooted. SG2 did find some but did not display any of the PUPPY ISOs.

Again using "/mnt/sdb1" and "HDD" is not very useful here. Try to use something more specific that I can understand. And, also, as you are using F2FS please specify your partition filesystem.

About not displaying PUPPY ISOs I have already answered to that:

> in the most common cases you need to make sure that a loopback.cfg is supplied inside the iso itself.

**Comment by adrian15** [comment] 2019-11-03 10:16
> Lastly, on GIT at this location ( [puppylinux-woof-CE/woof-CE#1618 (comment)](https://github.com/puppylinux-woof-CE/woof-CE/issues/1618#issuecomment-548973021) ) PUP developers are trying to achieve something I think @adrian15 has knowledge to make their life easy as they try to standardize on GRUB2. In fact for a 16MB SG2, Puppy could make SG2 its boot-loader to reduce their efforts in GRUB2 use.
> 
> If considered, SG2 could become their bootmanager and it would expand the number of SG2 developers working in concert here.

If you have any doubts on how to use Grub2 please use the grub-devel mailing list.
If you have any doubts on how to use SG2D you already know how to create a new issue on github.

The thread is interesting but I'm not going to help there actively. They can use Grub2 for BIOS, UEFI and SecureBoot UEFI boot if they want to. Using SG2D once they manage to include a proper isolinux.cfg file might help a bit but I think it's an overkill to be included as a default part of puppy.

**Comment by CollaboratorGCM** [comment] 2019-11-03 10:19
The developers on that thread will need to know how to create a loopback.cfg.

In any event, I have downloaded and rewritten the USB with the IMG contain in the downloaded ZIP. I am now in the process of moving all ISOs to /boot/boot-isos on the 2nd partition of the HDD.

It will take me approx one-half hours. 

Will post results once I take down the PC for testing the latest.

**Comment by adrian15** [comment] 2019-11-03 10:28
> The developers on that thread will need to know how to create a loopback.cfg.

If they have any problem with the current documentation they should create an issue here for asking for additional help. As I said I'm not going to help in an active manner.

**Comment by CollaboratorGCM** [comment] 2019-11-03 10:30
Oh oh, I see something different than before. 

There is no ISO9660 format. There are now 2 partitions on the USB stick which mount as /mnt/sdc1 and /mnt/sdc2 in my Linux. The USB stick is written as a MSDOS disk.

The first partition has 3 folders /boot /EFI /LIVEID
The second partition has 1 folder /BOOT-ISOS
(spellings has exact capitalizations as shown above)

I have 28GB of unallocated space.

Would you advise that I create a new EXT4 partition that has a folder /boot/boot-isos (not capitalizied)?

**Comment by adrian15** [comment] 2019-11-03 10:32
>  I am now in the process of moving all ISOs to /boot/boot-isos on the 2nd partition of the HDD.

Do you mean copying all the ISOs to /BOOTISOS folder on the 2nd partition of the USB ?

**Comment by adrian15** [comment] 2019-11-03 10:43
> I have 28GB of unallocated space.
> 
> Would you advise that I create a new EXT4 partition on that unallocated area of the USB that has a folder /boot/boot-isos (not capitalizied)?

If you read the README file found inside the second partition /BOOTISOS you will see:

```
1) Put here your GNU/Linux distribution isos based on:
loopback.cfg
and Super Grub2 Disk will find them and offer you to boot them.

More information at:
https://www.supergrubdisk.org/wiki/Loopback.cfg

2) You can use gparted or another tool to extend this second partition
to fill your usb device.
You will have to unmount or extract in a saffer manner the device
before running gparted (or similar tool).
```

Although it's not documented for this specific image as an advanced user you can delete the FAT32 BOOTISOS partition and create another EXT4 partition which has the /BOOTISOS (or any other of the four supported paths) folder.

You might want to add an additional FAT32 partition so that you can work with the USB from Windows. It's up to you.

Pull requests improving https://github.com/supergrub/supergrub/blob/41ed97fd1742b9435626a8bec4e60c9dda609d1e/supergrub-mkcommon#L309-L321 are welcome.

**Comment by CollaboratorGCM** [comment] 2019-11-03 10:47
I can expand that FAT32 partitions whose LABEL="SG2DISOS" to accomodate the PUP ISOs to that /BOOT-ISOS folder.

Is that a reasonable step at some point?

**Comment by CollaboratorGCM** [comment] 2019-11-03 10:51
OK, seems I am late. You have already answered tthe expanding question. Sorry.

**BTW** does it matter if the folder name is /boot-isos OR /BOOT-ISOS? Or does /BOOT-ISOS pertain to ISO files that have loopback.cfg

**Comment by adrian15** [comment] 2019-11-03 10:54
> OK, seems I am late. You have already answered tthe expanding question. Sorry.
> 
> **BTW** does it matter if the folder name is /boot-isos OR /BOOT-ISOS? Or does /BOOT-ISOS pertain to ISO files that have loopback.cfg

This is the code that answers your question:

https://github.com/supergrub/supergrub/blob/41ed97fd1742b9435626a8bec4e60c9dda609d1e/menus/sgd/autoiso.cfg#L253

**Comment by CollaboratorGCM** [comment] 2019-11-03 11:26
I had created 2 additional partitions on the USB stick: a NTFS primary partition labeled ISO1 and an extended area with single partition labeled ISO2. 

Next I copied ISO files to "/boot/boot-isos" on the NTFS partition. 

Removing the SD2 USB stick and plugging into a spare PC, I booted SG2 and selected the 2nd line item to search for bootables. It gave me a list of 'error' reads (probably bad USB issues) for the files on the NTFS partition where my ISO are. It did find the Windows OS on the PCs HDD.

I have erased the boot-isos directory on the NTFS partition and have now created the boot-isos directory on the EXT4 partition. When the ISO copy completes, I will retry SG2 on the other PC, again.

**Comment by adrian15** [comment] 2019-11-03 11:36
> I had created 2 additional partitions on the USB stick: a NTFS primary partition labeled ISO1 and an extended area with single partition labeled ISO2.
> 
> Next I copied ISO files to "/boot/boot-isos" on the NTFS partition.
> 
> Removing the SG2D USB stick and plugging into a spare PC, I booted SG2D and selected the 2nd line item to search for bootables. It gave me a list of 'error' reads (probably bad USB issues) for the files on the NTFS partition where my ISO are. It did find the Windows OS on the PCs HDD.

1) Getting some errors while SG2D is trying to find Operating systems is expected. I think SG2D had a recent addition which makes SG2D to output a message about those expected errors to be ignored.

2) Using the **Detect and show boot methods** option searches too many things.
You should use the **Boot manually** option and then the BOOTISOS one.

3) Anyways if  **Boot manually** **BOOTISOS** finds some isos but the **Detect and show boot methods** option does not find those same isos then it's a bug and it should be reported.

**Comment by adrian15** [comment] 2019-11-03 11:40
> Next I copied ISO files to "/boot/boot-isos" on the NTFS partition.

Make sure to add [rescatux-0.72-beta2.iso](https://sourceforge.net/projects/rescatux/files/rescatux-0.72-beta2/rescatux-0.72-beta2.iso/download) to your own isos so that you can verify the partitions are being detected ok.

**Comment by CollaboratorGCM** [comment] 2019-11-03 12:13
Thanks for the explanation of those error messages seen during the **Detect and show boot methods** search.

rescutux V0.72 beta 1 was already there and found. BUT as it started to desktop the X screen started wiht the mouse pointer visible, but the desktop never populated on that PC.

So, it looks like SG2 found the folder and the ONLY distros it presented was CAINE and RESCUTUX. None of the PUPs were presented (no loopback exist for them).

SG2 works. Your guidance and explanations have been clear. I will try (probably on Monday) to write a user perspective on what I have done to get a single USB setup to boot ISO files. I will tag it here as well as making it generally available.

**Comment by adrian15** [comment] 2019-11-03 12:22
> rescatux V0.72 beta 1 was already there and found.

Nice.

> BUT as it started to desktop the X screen started with the mouse pointer visible, but the desktop never populated on that PC.

You might need [Non free Rescatux](http://rescatux.sourceforge.net/repo/README.non-free.html) then.

> So, it looks like SG2D found the folder and the ONLY distros it presented was CAINE and RESCATUX. None of the PUPs were presented (no loopback exist for them).

Yes, that's the expected behaviour.

> SG2D works. Your guidance and explanations have been clear. I will try (probably on Monday) to write a user perspective on what I have done to get a single USB setup to boot ISO files. I will tag it here as well as making it generally available.

Nice.

**Comment by CollaboratorGCM** [comment] 2019-11-03 12:22
For this last rquest for guidance I ask. Would you or could you provide a sample loopback.cfg file for this Puppy Linux ===> https://distrowatch.com/table.php?distribution=puppy 

I could use it as a guide for many/most of the other PUPPY linux distros I use from time to time. Your process for booting a PC is so attractive I am amazed more of the LInux world are not using it. IMHO it should be a starter boot management facility in most distros. 

You may be ahead of your time.

**Comment by adrian15** [comment] 2019-11-03 12:24
> For this last rquest for guidance I ask. Would you or could you provide a sample loopback.cfg file for this Puppy Linux ===> https://distrowatch.com/table.php?distribution=puppy

No, please create a new issue for this request. I might need feedback from you and it seems offtopic for this issue.

**Comment by adrian15** [comment] 2019-11-03 12:30
> Your process for booting a PC is so attractive I am amazed more of the LInux world are not using it. IMHO it should be a starter boot management facility in most distros.
> 
> You may be ahead of your time.

1) If you are going to talk other people about loopback.cfg as being useful please refer them to https://github.com/rescatux/liveid too.

Actually it might be useful for some of you that you play with several puppy built usbs around in the same computer. So that one usb does not load another one by accident.

2) One important reason about using SG2D to carry ISOs around is that although it's quite old it has been less than one year since I managed to build an USB image that could be edited easily (compared to an ISO dd'ed to an USB).

And I'm focused on Rescatux so I don't care too much if people don't discover this new feature.

**Comment by CollaboratorGCM** [comment] 2019-11-03 12:33
P.S. Monday, I will try the following
move the USB to another PC and try to boot Rescutux
fi ift does not boot from SG2 USB, I will burn the Rescutux ISO to dvd and boot.

Will report then.

**Comment by adrian15** [comment] 2019-11-03 12:35
- Rescatux, not Rescutux
 - SG2D, not SG2

**Comment by adrian15** [comment] 2019-11-03 12:37
> P.S. Monday, I will try the following
> move the USB to another PC and try to boot Rescutux
> fi ift does not boot from SG2 USB, I will burn the Rescutux ISO to dvd and boot.
> 
> Will report then.

If you find any problem with it please open a new issue on [Rescatux issues](https://github.com/rescatux/rescatux/issues) .

**Comment by CollaboratorGCM** [comment] 2019-11-05 02:29
Tried the USB on a different desktop...success to desktop when selecting
Rescutux V0.72 ISO. SG2 works.

Thanks to you, I have a much better clarity in its operation.
[image: Desktop1.jpg]
[image: Desktop2.jpg]

**Comment by CollaboratorGCM** [comment] 2019-11-05 03:31
Tried the USB on a different desktop...**success to desktop** when selecting
Rescutux V0.72 ISO. SG2 works.

Thanks to you, I have a much better clarity in its operation.
![Rescutux ISO booted to PC: Desktop2](https://forum.vivaldi.net/assets/uploads/files/1572923733498-desktop1.jpg)
![Rescutux ISO booted to PC: Desktop2](https://forum.vivaldi.net/assets/uploads/files/1572923824337-desktop2.jpg)

**Comment by adrian15** [comment] 2019-11-05 22:17
> _**Its Monday**_
> Tried the USB on a different desktop...**success to desktop** when selecting
> Rescatux V0.72 ISO. SG2 works.
> 
> Thanks to you, I have a much better clarity in its operation.

Nice. Be sure to use to update to Rescatux 0.72-beta2 which has some bugs fixed.

**Comment by CollaboratorGCM** [comment] 2019-11-06 23:24
Done & Thanks. 

I will open a thread to request guidance to understanding how to build a functional loopback.cfg for an ISO that does not currently have one.

Thanks as this issues has been satisfied as I now have a better understanding of its requirements needed for ISO booting using SuperGRUB2

**Comment by CollaboratorGCM** [comment] 2019-11-06 23:37
Although this request is NOT considered addressing a SG2D bug, I am hopeful that its developers see a benefit that would be helpful to others who may have given up.

If its not to difficult, if SG2D analyzes its folders where ISOs are found, AND those ISOs are not the candidates it presents for booting, could SG2D make a red highlighted message that says "ISOs found that could not be processed by SG2D."

I now understand how some of the others have tried in the past for ISO/IMG booting and given up.

**Comment by adrian15** [comment] 2019-11-09 20:48
> I will open a thread to request guidance to understanding how to build a functional loopback.cfg for an ISO that does not currently have one.

Nice.

**Comment by adrian15** [comment] 2019-11-09 20:54
> If its not to difficult, if SG2D analyzes **its** folders where ISOs are found, AND its folders contains ISOs are not the candidates SG2D presents for booting, could SG2D make a red _highlighted message_ that says _"ISOs found that could not be processed by SG2D"_ .
> 
> I now understand how some of the others have tried in the past for ISO/IMG booting and given up.

This has already been asked in https://github.com/supergrub/supergrub/issues/50 .
Can you please open a new issue as a RFE so that we can track that new feature specifically?

Thank you.

**Comment by adrian15** [comment] 2019-11-09 20:56
> EDIT: UPDATE!!! This thread was opened with some bad understanding due in part by having trying to use the "wrong" SG2D. After being guided to the latest and proper SG2D ISO greater success was achieved.
> 
> In my case, the ONLY ISOs that I was able to have SG2D select for booting are the ONLY ones that have a loopback.cfg. ALL OTHER ISOs were ignored.

The issue was solved. We close the issue.

**Closed by adrian15** 2019-11-09 20:56 UTC
